language: generic
install:
  - curl -LO https://github.com/polyml/polyml/archive/v5.7.tar.gz
  - tar xf v5.7.tar.gz
  - cd polyml-5.7 && ./configure --prefix=/usr && make && sudo make install && cd ..
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - make test
